added option to disable flatten nested
ansible-collections/community.clickhouse pull request #63
Opened 2024-06-26 18:26 UTC by tmahany419

##### SUMMARY
I could not find a way to run multiple queries from the same context using this module. There's no way to create a table with `flatten_nested` disabled without running multiple queries. This PR adds a field called `flatten_nested` for `clickhouse_client` that sets this setting before running the query. 

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME

Flatten Nested

##### ADDITIONAL INFORMATION

This is clickhouse's document explaining options for nested fields: https://clickhouse.com/docs/en/sql-reference/data-types/nested-data-structures/nested. The behavior with `flatten_nested` enabled and disabled is explained there. The only way to disable it is by running `set flatten_nested=0;` before creating a table.

2024-06-28 06:53 UTC, Andersson007 requested changes
@tmahany419 hello, thanks for the PR!
Could you also please:
- Add a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment) 
- Add a test task to https://github.com/ansible-collections/community.clickhouse/blob/main/tests/integration/targets/clickhouse_client/tasks/initial.yml

thanks

2024-06-28 06:53 UTC, Andersson007 commented on plugins/doc_fragments/client_inst_opts.py
> +
```suggestion
  flatten_nested:
    description:
      - Sets the C(flatten_nested) setting on session before running the query.
    type: int
    choices: [0, 1]
    version_added: '0.5.0'
```
- this is the `clickhouse_client` related argument, so please move it to plugins/modules/clickhouse_client.py
- let's skip the default and let users specify it explicitly?

2024-06-28 06:53 UTC, Andersson007 commented on plugins/module_utils/clickhouse.py
> +        flatten_nested=dict(type='int', default=1),
```suggestion
        flatten_nested=dict(type='int'),
```
please move this to plugins/modules/clickhouse_client.py too

2024-06-28 06:53 UTC, Andersson007 commented on plugins/modules/clickhouse_client.py
> +        execute_query(module, client, "set flatten_nested=0;", execute_kwargs)
```suggestion
        execute_query(module, client, "SET flatten_nested = 0", execute_kwargs)
```

2024-06-28 21:45 UTC, tmahany419 commented
@Andersson007 Thank you for the feedback! I committed the changes you proposed. I've made unit test and it works against a local clickhouse db. I added it to the file you linked in the branch I am working on. Is there a way to test it before updating the PR?

2024-07-01 08:49 UTC, Andersson007 commented
> @Andersson007 Thank you for the feedback! I committed the changes you proposed. I've made unit test and it works against a local clickhouse db. I added it to the file you linked in the branch I am working on. Is there a way to test it before updating the PR?

@tmahany419 thanks!
About testing, yes, you can run the tests locally before pushing, please take a look at https://docs.ansible.com/ansible/devel/community/create_pr_quick_start.html , there are corresponding sections there

2024-07-01 08:50 UTC, Andersson007 commented on plugins/module_utils/clickhouse.py
> +        flatten_nested=dict(type='int'),
```suggestion
        flatten_nested=dict(type='int', choices=[0, 1]),
```

2024-07-03 10:49 UTC, Andersson007 commented
@tmahany419 I don't see the tests, maybe you forgot to add a change to your commit?

2024-07-03 12:50 UTC, tmahany419 commented
@Andersson007 I updated the wrong branch yesterday, it should be there now.

2024-07-03 17:23 UTC, merged

2024-07-04 07:43 UTC, aleksvagachev commented
@Andersson007 Maybe it is more correct to implement the transfer of not a specific parameter, but the desired list of parameters?

2024-07-04 08:06 UTC, Andersson007 commented
@aleksvagachev good catch, something like the following?
```
- name: Run the query
  community.clickhouse.clickhouse_client:
  query: SELECT ...
  set:
    flatten_nested: 0
```
?

2024-07-04 09:28 UTC, aleksvagachev commented
@Andersson007 Yes, something similar. Shall we try to implement this in 1.0.0?

2024-07-04 10:56 UTC, Andersson007 commented
> @Andersson007 Yes, something similar. Shall we try to implement this in 1.0.0?

@aleksvagachev as this change hasn't been released yet, we can do it right now. Thoughts? Would you like to take it?

2024-07-05 07:00 UTC, aleksvagachev commented
@Andersson007 I'll try to do it, but not before Monday